### ISSUE TITLE
problem with line 6, 7, 8

### ISSUE THREAD

**Issue by Talgami** [LukaShvangiradze/FoPProject#3]
I don't like the test, let's remove it

**Comment by LukaShvangiradze** [comment]
ok

**Comment by Talgami** [comment]
actually, let's do whatever, this is the testing phase as is

**Comment by LukaShvangiradze** [comment]
I agree

**Comment by Talgami** [comment]
now I will close this issues section as we've solved this problem already

**Comment by sandro140** [comment]
i agree aswell
